config/routes.rb
Rails.application.routes.draw do
  get 'winners/index'
  root to: 'pages#home'

  devise_for :users
  resources :users, param: :username do
    resources :guesses, only: [:index, :new, :create]
  end

  resources :treasures, only: [:index, :show] do
    resources :guesses, only: [:create]
  end
  
  resources :winners, only: [:index]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :authenticate_user!

  def index
    @guesses = current_user.guesses.page(params[:page]).per(10)
  end

  def new
    @guess = Guess.new
    @current_treasure = Treasure.current_treasure
    @has_won = current_user.has_won?
  end

  def create
    @guess = current_user.guesses.build(guess_params)
  
    if @guess.save
      if @guess.winner?
        WinnerNotificationJob.perform_async(current_user.id)
        redirect_to new_user_guess_path(current_user), notice: "You won!"
      else
        redirect_to new_user_guess_path(current_user), notice: "Not the treasure!"
      end
    else
      render :new
    end
  end

  private

  def guess_params
    params.require(:guess).permit(:latitude, :longitude)
  end
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/views/guesses/index.html.erb
<h1>Your Guesses</h1>

<% if @guesses.any? %>
  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Treasure</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Winner</th>
        <th>Distance to Treasure</th>
      </tr>
    </thead>
    <tbody>
      <% @guesses.each do |guess| %>
        <tr>
          <td><%= guess.user.username %></td>
          <td><%= guess.treasure.name %></td>
          <td><%= guess.latitude %></td>
          <td><%= guess.longitude %></td>
          <td><%= guess.winner ? 'Yes' : 'No' %></td>
          <td><%= number_with_precision(guess.distance_to_treasure, precision: 2) %> meters</td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2>No guesses yet!</h2>
<% end %>

<% unless current_user.has_won? %>
  <%= link_to 'Create New Guess', new_user_guess_path(current_user.username) %>
<% end %>

<%= link_to "Winners", winners_path %>
<%= paginate @guesses %>

app/views/guesses/new.html.erb
<style>
  #map {
    height: 400px;
    width: 100%;
  }
</style>

<div id="map"></div>

<h1>Aye Matey!</h1>
<p>Click the map to guess where the treasure is. You need to be within 1000 meters of the treasure to win!</p>

<%= form_with model: [current_user, @guess], url: user_guesses_path(username: current_user.username), local: true do |form| %>
  <% if @guess.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guess.errors.count, "error") %> prohibited this guess from being saved:</h2>

      <ul>
      <% @guess.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :latitude, id: 'guess_latitude' %>
  <%= form.hidden_field :longitude, id: 'guess_longitude' %>

  <div class="actions">
    <%= form.submit "Submit!", disabled: @has_won %>
  </div>
<% end %>

<%= link_to "Your Guesses", user_guesses_path(current_user.username) %>

<script>
  let map;
  let marker;

  function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
      center: { lat: 15.0, lng: -75.0 },
      zoom: 5,
      scrollwheel: false,
      draggable: true,
    });

    map.addListener("click", (mapsMouseEvent) => {
      if (marker) {
        marker.setMap(null);
      }

      marker = new google.maps.Marker({
        position: mapsMouseEvent.latLng,
        map: map,

        icon: "<%= asset_path('pirate_sm.png') %>"
      });

      const clickedLat = mapsMouseEvent.latLng.lat();
      const clickedLng = mapsMouseEvent.latLng.lng();
      document.getElementById('guess_latitude').value = clickedLat;
      document.getElementById('guess_longitude').value = clickedLng;
    });
  }
</script>

<%# TODO: this API key is a demo key that I've since deactivated but a new key needs to be added %>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=REPLACE_ME&callback=initMap" type="text/javascript"></script>